### ISSUE TITLE
Select the same date error

### ISSUE THREAD

**Issue by Avishaidev** [vlio20/angular-datepicker#151]
When i select first time the date its ok and then if i select again the same date i got error:
Runtime Error
Cannot read property 'format' of undefined

TypeError: Cannot read property 'format' of undefined
    at UtilsService.convertFromMomentArray (http://localhost:8100/build/vendor.js:223297:32)
    at DatePickerComponent.processOnChangeCallback (http://localhost:8100/build/vendor.js:223878:34)
    at DatePickerComponent.set [as selected] (http://localhost:8100/build/vendor.js:223797:40)
    at DatePickerComponent.dateSelected (http://localhost:8100/build/vendor.js:223991:23)
    at Object.eval [as handleEvent] (ng:///DpDatePickerModule/DatePickerComponent.ngfactory.js:331:24)
    at Object.handleEvent (http://localhost:8100/build/vendor.js:12274:138)
    at Object.handleEvent (http://localhost:8100/build/vendor.js:12977:85)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9174:21)
    at http://localhost:8100/build/vendor.js:11102:20
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/vendor.js:4223:36)

**Comment by vlio20** [comment]
What directive/component are you using day/month/daytime/time?

**Comment by Avishaidev** [comment]
dp-date-picker

**Comment by Avishaidev** [comment]
in your [demo](https://vlio20.github.io/angular-datepicker/) when you select the same date the onSelectEvent not fires but in my directive its fires this is the problem

**Comment by vlio20** [comment]
What mode?

**Comment by Avishaidev** [comment]
day

**Comment by vlio20** [comment]
You are selecting by click, right?

**Comment by Avishaidev** [comment]
yes

**Comment by vlio20** [comment]
Sorry, I can't reproduce this issue.
Please provide a demo - will close for now.
