### ISSUE TITLE
EXCEPTION: element.addEventListener is not a function

### ISSUE THREAD

**Issue by amirensit** [vlio20/angular-datepicker#157]
element.addEventListener is not a function 
any idea ??

**Comment by vlio20** [comment]
Amir, please give more details.

**Comment by amirensit** [comment]
`EXCEPTION: element.addEventListener is not a function
ErrorHandler.handleError @ core.umd.js:3064
next @ core.umd.js:8041
schedulerFn @ core.umd.js:3689
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:3675
NgZone.triggerError @ core.umd.js:4040
onHandleError @ core.umd.js:4001
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
data.args.(anonymous function) @ zone.js:1581
core.umd.js:3069 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ core.umd.js:3069
next @ core.umd.js:8041
schedulerFn @ core.umd.js:3689
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:3675
NgZone.triggerError @ core.umd.js:4040
onHandleError @ core.umd.js:4001
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
data.args.(anonymous function) @ zone.js:1581
core.umd.js:3070 TypeError: element.addEventListener is not a function
    at DomEventsPlugin.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3385:21)
    at EventManager.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2590:27)
    at DomRenderer.listen (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3052:52)
    at DatePickerComponent.startGlobalListeners (http://localhost:3000/node_modules/ng2-date-picker/date-picker/date-picker.component.js:259:59)
    at DatePickerComponent.set [as areCalendarsShown] (http://localhost:3000/node_modules/ng2-date-picker/date-picker/date-picker.component.js:55:22)
    at eval (http://localhost:3000/node_modules/ng2-date-picker/date-picker/date-picker.component.js:202:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:367:31)
    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:3971:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:366:36)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:47)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:420:38)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1581:29)
ErrorHandler.handleError @ core.umd.js:3070
next @ core.umd.js:8041
schedulerFn @ core.umd.js:3689
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:3675
NgZone.triggerError @ core.umd.js:4040
onHandleError @ core.umd.js:4001
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420
data.args.(anonymous function) @ zone.js:1581
Subscriber.ts:241 Uncaught TypeError: element.addEventListener is not a function
    at DomEventsPlugin.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3385:21)
    at EventManager.addEventListener (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2590:27)
    at DomRenderer.listen (http://localhost:3000/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3052:52)
    at DatePickerComponent.startGlobalListeners (http://localhost:3000/node_modules/ng2-date-picker/date-picker/date-picker.component.js:259:59)
    at DatePickerComponent.set [as areCalendarsShown] (http://localhost:3000/node_modules/ng2-date-picker/date-picker/date-picker.component.js:55:22)
    at eval (http://localhost:3000/node_modules/ng2-date-picker/date-picker/date-picker.component.js:202:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:367:31)
    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:3971:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:366:36)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:47)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:420:38)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1581:29)`

**Comment by vlio20** [comment]
I mean steps to reproduce

**Comment by vlio20** [comment]
I will close this for now
