### ISSUE TITLE
Not able to bind to moment, getting TypeError: (value || "").split is not a function

### ISSUE THREAD

**Issue by cyates81** [vlio20/angular-datepicker#355]
Hello,

I am using Angular 5, moment 2.20.1, Chrome 64, Mac High Sierra.  I updated to version 2.7.4 and now I get the following stack trace:

Uncaught (in promise): TypeError: (value || "").split is not a function
TypeError: (value || "").split is not a function
    at UtilsService.datesStringToStringArray (http://localhost:8100/build/vendor.js:44895:30)
    at DatePickerService.isValidInputDateValue (http://localhost:8100/build/vendor.js:211582:45)
    at DatePickerComponent.onViewDateChange (http://localhost:8100/build/vendor.js:92223:35)
    at http://localhost:8100/build/vendor.js:129065:34
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/vendor.js:4586:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:63973:16)
    at SafeSubscriber.next (http://localhost:8100/build/vendor.js:63920:22)
    at Subscriber._next (http://localhost:8100/build/vendor.js:63860:26)
    at Subscriber.next (http://localhost:8100/build/vendor.js:63824:18)
    at EventEmitter.Subject.next (http://localhost:8100/build/vendor.js:64060:25)

The only way I can prevent this is to bind to a string which is not ideal.  Thanks for your help.

**Comment by cyates81** [comment]
For more info, I had updated from 2.3.2 up to 2.7.4 when I experienced the bug.  I decided to downgrade to 2.3.2 and incrementally test each version to figure out where it stopped working and 2.5.0 is where it no longer works with the moment object.  The error is slightly different, however: TypeError: value.split is not a function.  For now I will just use version 2.4.0

**Comment by vlio20** [comment]
It would be great if you could create a stackblitz with your configuration.

**Comment by cyates81** [comment]
https://ionic-8csbwc.stackblitz.io/

The error will show in console.  It appears to still work someone on stackblitz but when running from ionic serve it brings the error window up and then doesn't function properly.

**Comment by vlio20** [comment]
@cyates81 can u please share the link to stackblitz editor instead of the preview?

**Comment by cyates81** [comment]
https://stackblitz.com/edit/ionic-8csbwc

**Comment by vlio20** [comment]
As a workaround I suggest to do as follows https://stackblitz.com/edit/ionic-qa1cjj

I will mark it as bug, I hope I will have the time to address this issue in the next few days.

**Comment by vlio20** [comment]
fixed, will be available in version 2.7.5

**Comment by cyates81** [comment]
Much appreciated!
