### ISSUE TITLE
Can't use it in angular 8 with Ivy

### ISSUE THREAD

**Issue by BlindDespair** [vlio20/angular-datepicker#456]
- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.

- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [x] What's the **version** of Angular you're using?
Angular CLI: 8.0.0
Node: 10.16.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
- [ ] Does this occur on specific browser?

I installed this date picker to try it out in my project, but it throws error as soon as I try to open it. I need a date picker to use in my modal window which is part of a lazy loaded module, which explains why I got the error. It looks like this:
```
ERROR NullInjectorError: R3InjectorError(AppModule)[UtilsService]: 
  StaticInjectorError(AppModule)[UtilsService]: 
    StaticInjectorError(Platform: core)[UtilsService]: 
      NullInjectorError: No provider for UtilsService!
    at NullInjector.get (http://localhost:4200/vendor.js:26173:27)
    at resolveToken (http://localhost:4200/vendor.js:26500:24)
    at tryResolveToken (http://localhost:4200/vendor.js:26426:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:26289:20)
    at resolveToken (http://localhost:4200/vendor.js:26500:24)
    at tryResolveToken (http://localhost:4200/vendor.js:26426:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:26289:20)
    at R3Injector.get (http://localhost:4200/vendor.js:43485:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:51942:33)
    at Object.get (http://localhost:4200/vendor.js:49822:35)
```
Problem with this is that lazy loaded module gets its own instance of UtilsService, but there is a bug in injector, which doesn't properly delegate parent injector to an entryComponent which I recently opened [issue](https://github.com/angular/angular/issues/31819) about.

Adding DpDatePickerModule to imports of app.module fixes this problem, but produces another one. However, regardless of that why do I need to have a new instance of this service for each lazy loaded module? I believe this kind of service should always be singleton. Please, consider using `forRoot` practice instead of providing your services directly in your module. Because otherwise now I'll have different instance of service in component of my lazy loaded module and in my modal window. I can work it around, but I think it has to be fixed in the module.

Now back to issue I get after add import to my app.module. The I am getting error that looks like this:
```
ERROR NullInjectorError: R3InjectorError(AppModule)[Renderer]: 
  StaticInjectorError(AppModule)[Renderer]: 
    StaticInjectorError(Platform: core)[Renderer]: 
      NullInjectorError: No provider for Renderer!
    at NullInjector.get (http://localhost:4200/vendor.js:26173:27)
    at resolveToken (http://localhost:4200/vendor.js:26500:24)
    at tryResolveToken (http://localhost:4200/vendor.js:26426:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:26289:20)
    at resolveToken (http://localhost:4200/vendor.js:26500:24)
    at tryResolveToken (http://localhost:4200/vendor.js:26426:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:26289:20)
    at R3Injector.get (http://localhost:4200/vendor.js:43485:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:51942:33)
    at Object.get (http://localhost:4200/vendor.js:49822:35)
```
Renderer is long deprecated and Renderer2 should be used. I tried to quickly hack it by doing something like `{provide: Renderer, useClass: Renderer2`}, and I managed to get rid of error above, but of course I got a storm of other errors...

**Comment by danielzach** [comment]
I'm having exactly the same issue, when using Ivy... @vlio20 any update on this?

**Comment by vlio20** [comment]
No updates yet. Hope to have some time to fix this issue

**Comment by vlio20** [comment]
I replaced renderer with renderer2. This will be available in the nest version.

**Comment by TxusBlack** [comment]
Re-update?

**Comment by vlio20** [comment]
@TxusBlack not sure that the current version can run with ng8
