### ISSUE TITLE
Error occurs cannot read property kind of undefined in build optimizer

### ISSUE THREAD

**Issue by archerchiu** [vlio20/angular-datepicker#495]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [x] Provide **screenshots** where appropriate
```
ERROR in ./node_modules/ng2-date-picker/fesm5/ng2-date-picker.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\projects\eform-main\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (D:\projects\eform-main\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (D:\projects\eform-main\node_modules\typescript\lib\typescript.js:16631:30)
......
```
- [x] What's the **version** of Angular you're using?
```
"@angular/common": "8.2.5",
"@angular/compiler": "8.2.5",
"@angular/core": "8.2.5",
......
"ng2-date-picker": "8.0.0"
......
```
- [x] Does this occur on specific browser?
Occurs the error as build --prod, has no related with browsers.

I know that can ignore the error through close buildOptimizer parameter in angular.json, but this is not what I want. Have any suggestion for this error?

**Comment by vlio20** [comment]
Hi, @archerchiu can you please post a small repo with the reproduction of this issue?

**Comment by archerchiu** [comment]
Hi, @vlio20 thank you for response.

I add a repository on [https://github.com/archerchiu/date-picker-repo](url)
Creating by angular-cli and add some libraries to package.json to serve on 4500 port.
Main page can see the dpDayPicker component works normally.
But, error occurred when I was building.
```
ERROR in ./node_modules/ng2-date-picker/fesm2015/ng2-date-picker.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\projects\date-picker-repo\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (D:\projects\date-picker-repo\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:16859:24)
    at transformer (D:\projects\date-picker-repo\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:39:16)
    at transformSourceFileOrBundle (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:67384:57)
    at transformation (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:83586:24)
    at transformRoot (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:83606:82)
    at Object.map (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:499:29)
    at Object.transformNodes (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:83593:30)
    at emitJsFileOrBundle (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:84089:32)
    at emitSourceFileOrBundle (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:84043:13)
    at forEachEmittedFile (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:83832:34)
    at Object.emitFiles (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:84026:9)
    at emitWorker (D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:89951:33)
    at D:\projects\date-picker-repo\node_modules\typescript\lib\typescript.js:89912:66
```

**Comment by vlio20** [comment]
@archerchiu looks fine to me:
https://stackblitz.com/edit/github-bc6hwa?file=src/app/app.component.ts

There is some issue with importing moment but it seems not to be related to the lib.
